### PR TITLE
LRDOCS-6326 migrating Liferay data to a new database

### PR DESCRIPTION
**Pull request by jhinkey**
Hi @achaparro ,

Would you review these data migration steps and changes for 7.0?

https://issues.liferay.com/browse/LRDOCS-6326

### CODE REVIEW

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @jhinkey,

I am having several issues trying to rebase your pull, do you know why? do you think that sending again the pull will solve it?

Thanks.

**Comment by jhinkey** [comment]
Hey Alberto, 

We don't typically rebase on liferay-docs.

My changes for review are all in https://github.com/achaparro/liferay-docs/pull/28/commits/0546ebe84ef179d627a892b9cc4010c0657ba427

Let me know if there's something in particular you can't see or want to do. Thanks.

Jim

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/jhinkey/liferay-docs/pull/436. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @jhinkey,

Understood. Pull sent.

Thanks.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/jhinkey/liferay-docs/pull/438. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
