### PR TITLE
upgrading liferay to 7.2

### PR DESCRIPTION
**Pull request by jhinkey**
Hey Alberto!

Here are the doc locations. If you would, please review the upgrade articles, as I'd like to work towards publishing them. The articles on [upgrading the data](https://github.com/jhinkey/liferay-docs/tree/72-upgrading-liferay/deployment/articles/05-upgrading-to-liferay-7-2/06-upgrading-the-liferay-database) and [post-upgrade tasks](https://github.com/jhinkey/liferay-docs/blob/72-upgrading-liferay/deployment/articles/05-upgrading-to-liferay-7-2/07-executing-post-upgrade-tasks.markdown) are new since the [last PR](https://github.com/achaparro/liferay-docs/pull/29) you reviewed.   Thanks!

Note, I haven't yet worked on the database tuning docs. 

Data upgrade articles: https://github.com/jhinkey/liferay-docs/tree/72-upgrading-liferay/deployment/articles/05-upgrading-to-liferay-7-2

Upgrade Plan: https://github.com/jhinkey/liferay-docs/blob/72-upgrading-liferay/deployment/articles/100-reference/06-liferay-upgrade-plan.markdown

### CODE REVIEW

**Comment by achaparro** [comment]
Hey @jhinkey,

Sorry for the delay, I will start working on this now.

Thanks.

**Comment by jhinkey** [comment]
@achaparro ,

Note, I still have to write the DB tuning article based on your draft. 

I plan to put it just before the article on configuring your database upgrade...

- Upgrading the @product@ data
    - Tuning your database for the upgrade
    - Configuinge the data upgrade
    ...

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jhinkey** [comment]
FYI - After you review this, I'll add the dl.store.impl portal-upgrade-ext.properties changes we did for 7.1.

**Comment by jhinkey** [comment]
Hi @achaparro ,

Let's keep the current the order (i.e., preparing your new server and then upgrading the Liferay database). The main reason is that several of the instructions for preparing a new server are essential for upgrading the DB: installing 7.2, getting an upgrade patch, disabling indexing. Whether the admin eventually uses this server as the new production server is completely up to that admin. 

Any other review comments?

Thanks!
Jim

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/jhinkey/liferay-docs/pull/446. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
