### PR TITLE
LRDOCS-1974 Upgrade wordmithing and edits

### PR DESCRIPTION
**Pull request by sez11a**
Hey Alberto,

Here are the changes I made to the docs you submitted. If you have updates to make, please make them in this version. If there's anything I can do to help, please let me know. It looks like you may need to merge in master first.

### CODE REVIEW

**Comment by vicnate5** [comment]
@sez11a There is some information in this document that conflicts with information QA has about upgrading

1. Upgrading directly from 6.0, 6.1, or 6.2 are all supported by the upgrade process.
2. Indexing must be re-enabled after upgrading (See https://github.com/sez11a/liferay-docs/pull/1614#issuecomment-215483637). Failure to explicitly disable can lead to issues.
3. This needs clarification or more information, `The upgrade tool can be found in the tools folder, in a folder called portal-tools-db-upgrade-client`. As of now, the current release build process does not include the tools folder. The upgrade tool is distributed in a standalone zip file.
4. `--noShell or -n: disables connection to the Gogo shell during upgrades` This command no longer exists. It has been replaced by a command that always enables the shell `--shell` or `-s`. The upgrade tool no longer connects to the gogo shell by default unless one of the modules upgrades fails to complete.
5. `upgrade:dryRun: list upgrades pending to execute because they failed in the past` This command has been replaced by `upgrade:check`.

@achaparro Please let me know if any of this information I have is incorrect or out of date.

Thanks guys!

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @vicnate5,

The information is correct, I will update the docs with it before sending it to @sez11a again.

Thanks!

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
https://github.com/sez11a/liferay-docs/pull/1660

**Pull request closed without merging**
