### PR TITLE
Revised liferay upgrade plan

### PR DESCRIPTION
**Pull request by jhinkey**
I revised the plan to improve the sections and reduce overlap. Also added checkpoints. cc @gamerson

- Test upgrading a database copy (it's up front that we're testing things here)
- Prepare to upgrade the production database (testing is done, it's time to remove the noted unused entities and make last minute preparations)
- Prepare a new production server (can be done in parallel with previous sections)
- Upgrade the database (the test section uses this too)
- Execute post-upgrade tasks.

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @jhinkey,

Thanks for the update.

One note regarding the changes, I think we have lost the idea of removing unused data, test it and put that in production in the original version before the upgrade:
https://github.com/achaparro/liferay-docs/blob/703508bf5b48821212154eeefaeca6ae8ff8ea62/deployment/reference/articles/05-liferay-upgrade-plan.markdown

Maybe we are saying this here:
Checkpoint: Noted all unused entities to remove from production

But we should be more explicit since it's really important that they remove them, test the portal after that and go live in the original version (with the proper backup) before the upgrade. Otherwise we can get errors during the upgrade that can be caused due to a bad removal of data.

Let me know what you think.

@gamerson

**Comment by jhinkey** [comment]
Hi @achaparro ,

I see your point. I inserted steps to test (the test and prod servers) against the pruned database before upgrading. How is that?

Thanks!

**Comment by achaparro** [comment]
Hey @jhinkey,

It looks good from my point of view now.

Thanks!

**Comment by jhinkey** [comment]
Hi @achaparro ,

In the section on preparing your new server with 7.2, I added a step to configure your d & m file store. See https://github.com/achaparro/liferay-docs/pull/29/commits/f6bba1be55328b6cf7756668213a22382f63ac2c. And the step before it has them migrate (and update) their current portal properties to the new server. Won't it be sufficient for admins to do this in their portal properties and OSGi configs? Why would the upgrade tool also need a `dl.store.impl` property in a `portal-upgrade-ext.properties` file?

Thanks

**Comment by achaparro** [comment]
Hey @jhinkey,

The upgrade tool needs the property dl.store.impl property in a portal-upgrade-ext.properties file because this tool does not read the regular portal-ext.properties. All needed properties for the upgrade need to be set in the portal-upgrade-ext.properties and this is important because in the upgrade process we modify and move documents.

I like the idea of having a specific point for the DL configuration here: https://github.com/achaparro/liferay-docs/commit/f6bba1be55328b6cf7756668213a22382f63ac2c and I guess we should complete the point the point II.v.b saying:

- Copy database properties from portal-ext.properties to portal-upgrade-database.properties
- Copy rest of the properties from portal-ext.properties to portal-upgrade-ext.properties and also configure liferay.home
- Configure app-server.properties

or point out to the article in the documentation which says that.

What do tou think?

Thanks.

**Comment by jhinkey** [comment]
@achaparro I'll add those steps to the respective article: https://issues.liferay.com/browse/LRDOCS-6117

**Comment by achaparro** [comment]
Great @jhinkey! Thanks!

**Pull request closed without merging**
